### ISSUE TITLE
So great so needed! Not a single native PopupMneu solution out there

### ISSUE THREAD

**Issue by Noitidart** [prscX/react-native-popover-menu#2]
Thank you so much for this!! I have been looking for an Android popup style that agrees with native PopupMenu look and you gave the the native PopupMenu itself! Thank you!

I was trying to use stuff like this - `https://github.com/mxck/react-native-material-menu/issues/12`

Way bonus is the iOS perfect popover menu!

**Comment by prscX** [comment]
Thanks @Noitidart for the appreciation 👍 😄

**Comment by Noitidart** [comment]
Thank you my man!! I was looking for ages and tried all kinds of other js only solutions but it was so not the native feel. I tried:

* https://github.com/instea/react-native-popup-menu
* https://github.com/mxck/react-native-material-menu
* https://github.com/instea/react-native-popup-menu

They felt so bad, so I then tired and struggled to try to write my own Native UI Component for popover from here - https://developer.android.com/guide/topics/ui/menus.html#PopupMenu - totally failed. And then found your module just yesterday!! And it comes with iOS bonuses!! <3 <3 <3

**Comment by prscX** [comment]
Completely agree with your concern @Noitidart, but native bridge will always come with few limitation such as:

- We have to trade on few features, since we might not find exact libraries on both Android & iOS.
- Maintains is difficult, since both platform libraries are written in native and by different contributors.

But I am doing a trade on features rather then on look and feel. For projects which I am working on it fulfils the need 😄 

Thanks
Pranav

**Comment by prscX** [comment]
I am looking into other issues as well which you have raised. I will revert back ASAP 😄 

Thanks
Pranav

**Comment by Noitidart** [comment]
Thanks @prscX ! I'm very excited to use this. I just woke up and first thing I checked was here :D No rush though please, you maintain so many things. We are all thankful to you and the others for these amazing works!
