### ISSUE TITLE
[FR][Android] tintColor/darkmode for Android

### ISSUE THREAD

**Issue by danielang** [prscX/react-native-popover-menu#9]
Hey @prscX 
this is a feature-request. It would be very nice if we can theme the Popover on Android.
Is this possile?

The native library has the capability for that:
![DarkTheme](https://raw.githubusercontent.com/zawadz88/MaterialPopupMenu/master/art/sample_toolbar_dark.png)

Thank you!

**Comment by prscX** [comment]
Thanks @danielang for raising the query.

Definitely it is possible, may be we can expose a theme prop and based on this we apply the standard theme.

Coming weekend I will try to enable this feature or in case you are interested to take this up, please feel free to raise PR for the same.

Thanks
Pranav

**Comment by danielang** [comment]
Hey @prscX,
this would be so awesome! Thank you!

**Comment by prscX** [comment]
Hi @danielang,

I have enabled theme support but I am experiencing few issue with native library in order to set dark theme programatically. I have raised the same to [MaterialPopupMenu: 12](https://github.com/zawadz88/MaterialPopupMenu/issues/12), once it is resolved we will be able to set theme dynamically.

I will keep you posted.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @danielang, 

I have enabled `dark` theme support on Android. Can you please download `v0.0.8` and  verify the same.

Let me know in case you face any issues.

Thanks
Pranav
